//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon_Skills_2015.Data_Folder
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Event
    {
        public string EventId { get; set; }
        public string EventName { get; set; }
        public string EventTypeId { get; set; }
        public byte MarathonId { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<short> MaxParticipants { get; set; }
    }
}
